// +build !ignore_autogenerated

/*
Copyright 2018 The Openshift Evangelists

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*HORHPAMemory).DeepCopyInto(out.(*HORHPAMemory))
			return nil
		}, InType: reflect.TypeOf(&HORHPAMemory{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*HORHPAMemoryList).DeepCopyInto(out.(*HORHPAMemoryList))
			return nil
		}, InType: reflect.TypeOf(&HORHPAMemoryList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*HPAMemorySpec).DeepCopyInto(out.(*HPAMemorySpec))
			return nil
		}, InType: reflect.TypeOf(&HPAMemorySpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*HPAMemoryStatus).DeepCopyInto(out.(*HPAMemoryStatus))
			return nil
		}, InType: reflect.TypeOf(&HPAMemoryStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HORHPAMemory) DeepCopyInto(out *HORHPAMemory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HORHPAMemory.
func (in *HORHPAMemory) DeepCopy() *HORHPAMemory {
	if in == nil {
		return nil
	}
	out := new(HORHPAMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HORHPAMemory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HORHPAMemoryList) DeepCopyInto(out *HORHPAMemoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HORHPAMemory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HORHPAMemoryList.
func (in *HORHPAMemoryList) DeepCopy() *HORHPAMemoryList {
	if in == nil {
		return nil
	}
	out := new(HORHPAMemoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HORHPAMemoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAMemorySpec) DeepCopyInto(out *HPAMemorySpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.TargetMemoryPercentage != nil {
		in, out := &in.TargetMemoryPercentage, &out.TargetMemoryPercentage
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAMemorySpec.
func (in *HPAMemorySpec) DeepCopy() *HPAMemorySpec {
	if in == nil {
		return nil
	}
	out := new(HPAMemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAMemoryStatus) DeepCopyInto(out *HPAMemoryStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		if *in == nil {
			*out = nil
		} else {
			*out = new(meta_v1.Time)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.CurrentMemoryPercentage != nil {
		in, out := &in.CurrentMemoryPercentage, &out.CurrentMemoryPercentage
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAMemoryStatus.
func (in *HPAMemoryStatus) DeepCopy() *HPAMemoryStatus {
	if in == nil {
		return nil
	}
	out := new(HPAMemoryStatus)
	in.DeepCopyInto(out)
	return out
}
