/*
Copyright 2018 The Openshift Evangelists

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	horhpamemory_v1 "kube-hpamemory/pkg/apis/horhpamemory/v1"
	versioned "kube-hpamemory/pkg/client/clientset/versioned"
	internalinterfaces "kube-hpamemory/pkg/client/informers/externalversions/internalinterfaces"
	v1 "kube-hpamemory/pkg/client/listers/horhpamemory/v1"
	time "time"
)

// HORHPAMemoryInformer provides access to a shared informer and lister for
// HORHPAMemories.
type HORHPAMemoryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HORHPAMemoryLister
}

type hORHPAMemoryInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewHORHPAMemoryInformer constructs a new informer for HORHPAMemory type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHORHPAMemoryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.HorhpamemoryV1().HORHPAMemories(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.HorhpamemoryV1().HORHPAMemories(namespace).Watch(options)
			},
		},
		&horhpamemory_v1.HORHPAMemory{},
		resyncPeriod,
		indexers,
	)
}

func defaultHORHPAMemoryInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewHORHPAMemoryInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *hORHPAMemoryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&horhpamemory_v1.HORHPAMemory{}, defaultHORHPAMemoryInformer)
}

func (f *hORHPAMemoryInformer) Lister() v1.HORHPAMemoryLister {
	return v1.NewHORHPAMemoryLister(f.Informer().GetIndexer())
}
